[project]
name = "nanodrr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jaxtyping>=0.3.7",
    "matplotlib>=3.10.8",
    "torch>=2.10.0",
    "torchio>=0.21.2",
]

[project.optional-dependencies]
jupyter = [
    "jupyter-ruff>=0.3.1",
    "jupyterlab>=4.5.3",
    "jupyterlab-execute-time>=3.3.0",
]

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "diffdrr>=0.6.0",
]

[tool.ruff]
line-length = 120
lint.ignore = [
    "F722",  # Forward annotation false positive from jaxtyping
]